// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExtGuid
{
    internal sealed partial class Vsix
    {
        public const string Id = "ExtGuid.6d9a51ab-051c-4f42-b310-b9681488964e";
        public const string Name = "ExtGuid";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "AnderRester";
        public const string Tags = "";
    }
}
